# Model arguments
model_name_or_path: /hai/scratch/fangwu97/xu/SimPO_slurm/outputs/gemma-2-9b-it
torch_dtype: null
attn_implementation: eager

# Data training arguments
chat_template: "{{ bos_token }}{% if messages[0]['role'] == 'system' %}{% set system_message = messages[0]['content'] | trim + '\n\n' %}{% set messages = messages[1:] %}{% else %}{% set system_message = '' %}{% endif %}{% for message in messages %}{% if loop.index0 == 0 %}{% set content = system_message + message['content'] %}{% else %}{% set content = message['content'] %}{% endif %}{% if (message['role'] == 'assistant') %}{% set role = 'model' %}{% else %}{% set role = message['role'] %}{% endif %}{{ '<start_of_turn>' + role + '\n' + content | trim + '<end_of_turn>\n' }}{% endfor %}{% if add_generation_prompt %}{{'<start_of_turn>model\n'}}{% endif %}"
dataset_mixer:
  data/inpo_iter1_20k/pref: 1.0

dataset_splits:
- train
- test

preprocessing_num_workers: 12

# INPOTrainer arguments
bf16: true

eta: 0.0075
ratio: 0.5
max_history_t: 2

do_eval: true
evaluation_strategy: steps
eval_steps: 5
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False

log_level: info
logging_steps: 1
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
optim: adamw_torch
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
push_to_hub: false
save_strategy: "steps"
save_steps: 5
load_best_model_at_end: True
metric_for_best_model: "eval_loss"
report_to:
- wandb
save_total_limit: 2
seed: 42
warmup_ratio: 0.1
output_dir: ./outputs/gemma-2-9b-it_dpo_20k_stage_1
run_name: gemma-2-9b-it_dpo_20k_stage_1-sep21
learning_rate: 5.0e-7